DELETE http://localhost:4001/api/tickets/c9a12969-079c-493b-82c1-7a2eb3fe7d8d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjI2YjE3NWFiODY2MzcyZTQ3ZGE2MzQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTM4MTI5NDksImV4cCI6MTcxMzgxNjU0OX0.pO8Qp1CtEXbfHNvCdD8_Y7hk-_j4Cm4lCGp6DbNZWo8